/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    books: Book;
    events: Event;
    'press-quotes': PressQuote;
    media: Media;
    'form-submissions': FormSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    books: BooksSelect<false> | BooksSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'press-quotes': PressQuotesSelect<false> | PressQuotesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    tarotPage: TarotPage;
    decodingPage: DecodingPage;
    booksPage: BooksPage;
    eventsPage: EventsPage;
    contactPage: ContactPage;
    site: Site;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    tarotPage: TarotPageSelect<false> | TarotPageSelect<true>;
    decodingPage: DecodingPageSelect<false> | DecodingPageSelect<true>;
    booksPage: BooksPageSelect<false> | BooksPageSelect<true>;
    eventsPage: EventsPageSelect<false> | EventsPageSelect<true>;
    contactPage: ContactPageSelect<false> | ContactPageSelect<true>;
    site: SiteSelect<false> | SiteSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Your Decoding Sylvia Plath essays. To add one: click “Create New”, add the title, a picture and the text, then click Publish. Drag the ⋮⋮ handle in the list to change the order they appear in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  _order?: string | null;
  /**
   * The big heading at the top of the essay, e.g. “Street Song”: Double Jeopardy
   */
  title: string;
  /**
   * One picture for the essay (a photo, newspaper clipping, cartoon…). It is always shown in full — nothing gets cropped. When you upload it, the “Caption” you type appears under the picture.
   */
  heroImage?: (number | null) | Media;
  /**
   * Type or paste the essay here. Press Enter for a new paragraph. Use the buttons above for bold, italic or links.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional. Leave blank to use the day you publish.
   */
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  /**
   * Auto-filled from the title. Edit it to set a custom URL.
   */
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Images used across books, essays, pages, and the site. Use descriptive alt text so assets are easy to identify and accessible.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Shown under the picture on the website (and read aloud for people using screen readers). For a book cover, type the book title. For an essay picture, describe it, e.g. “Emmett Till in the 1956 newspaper headlines”.
   */
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * The books shown on your Books page. To add one: click “Create New”, fill in the details, then click Publish. Drag the ⋮⋮ handle in the list to change the order they appear in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books".
 */
export interface Book {
  id: number;
  _order?: string | null;
  title: string;
  /**
   * Optional — the line under the title, if the book has one.
   */
  subtitle?: string | null;
  /**
   * The front cover only (not the back or spine). When you upload it, type the book title in “Caption”.
   */
  coverImage: number | Media;
  publisher?: string | null;
  publishYear?: number | null;
  isbn?: string | null;
  /**
   * A short description. Press Enter for a new paragraph.
   */
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Each store becomes a “Buy from…” button on the book’s page. Click “Add Store”, pick the store, and paste the link to the book there.
   */
  retailers?:
    | {
        retailer: 'bookshop' | 'amazon' | 'barnesNoble' | 'publisher' | 'indiebound' | 'other';
        label?: string | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  pressQuotes?: (number | PressQuote)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  featured?: boolean | null;
  publishedAt?: string | null;
  /**
   * Auto-filled from the title. Edit it to set a custom URL.
   */
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The quotes shown in “In the Press” on your homepage. Open a quote to change its wording or who said it, then click Save — the preview beside it shows the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-quotes".
 */
export interface PressQuote {
  id: number;
  /**
   * Just the words, without quotation marks — the website adds them.
   */
  quote: string;
  /**
   * Who said it — e.g. "Riverfront Times" or "CBS Radio"
   */
  source: string;
  sourceUrl?: string | null;
  /**
   * e.g. "on Tarot Life Lessons" — shown in small type under the source
   */
  context?: string | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Events shown in “Upcoming Events” on your homepage. To add one: click “Create New”, fill in the details, then click Publish. An event drops off the website by itself after its date passes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * e.g. "Tarot Life Lessons — St. Louis Book Signing"
   */
  title: string;
  kind: 'reading' | 'signing' | 'lecture' | 'workshop' | 'fair' | 'media';
  startDate: string;
  /**
   * Set this for multi-day events like a weekend fair.
   */
  endDate?: string | null;
  /**
   * Shown on the event card, e.g. “Left Bank Books, St. Louis, MO”.
   */
  cityOverride?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * e.g. "Free, first come first served" or "$15 at the door"
   */
  ticketNote?: string | null;
  ticketUrl?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  featured?: boolean | null;
  publishedAt?: string | null;
  /**
   * Auto-filled from the title. Edit it to set a custom URL.
   */
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Messages people send you from the Contact page (you also get each one by email). Open a message to read it, and tick “Handled” once you’ve replied.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  reason: 'reading' | 'invite' | 'press' | 'general';
  message: string;
  /**
   * Check this off once you’ve replied or resolved it.
   */
  handled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Editors can publish everything but cannot manage other users or redirects.
   */
  role: 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'books';
        value: number | Book;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'press-quotes';
        value: number | PressQuote;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  heroImage?: T;
  content?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "books_select".
 */
export interface BooksSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  subtitle?: T;
  coverImage?: T;
  publisher?: T;
  publishYear?: T;
  isbn?: T;
  description?: T;
  retailers?:
    | T
    | {
        retailer?: T;
        label?: T;
        url?: T;
        id?: T;
      };
  pressQuotes?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  startDate?: T;
  endDate?: T;
  cityOverride?: T;
  description?: T;
  ticketNote?: T;
  ticketUrl?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-quotes_select".
 */
export interface PressQuotesSelect<T extends boolean = true> {
  quote?: T;
  source?: T;
  sourceUrl?: T;
  context?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  reason?: T;
  message?: T;
  handled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The words at the top of your homepage and in the “About” card near the bottom. Change the text, then press “Publish changes”. (Upcoming events and quotes are managed under “Add & edit”.)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Type first and last name. The last name automatically appears in italics.
   */
  heroHeading: string;
  /**
   * One short line, e.g. “Professional tarot card reader and author”.
   */
  heroSubheading?: string | null;
  /**
   * A few sentences shown beside your photo at the very top of the homepage.
   */
  heroRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The longer “About” card just above the footer. Press Enter for a new paragraph.
   */
  aboutRichText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'books';
                value: number | Book;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  modules?:
    (BioSplitBlock | BookShelfBlock | EventListBlock | PressStripBlock | PullQuoteBlock | CallToActionBlock)[] | null;
  /**
   * Falls back to the hero photo if left empty.
   */
  aboutImage?: (number | null) | Media;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BioSplitBlock".
 */
export interface BioSplitBlock {
  image: number | Media;
  imagePosition?: ('left' | 'right') | null;
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'books';
                value: number | Book;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bioSplit';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BookShelfBlock".
 */
export interface BookShelfBlock {
  heading?: string | null;
  /**
   * Choose specific books, or leave empty to automatically show books marked "Feature on homepage book shelf".
   */
  books?: (number | Book)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'bookShelf';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventListBlock".
 */
export interface EventListBlock {
  heading?: string | null;
  mode?: ('upcoming' | 'selected') | null;
  /**
   * How many upcoming events to show.
   */
  limit?: number | null;
  events?: (number | Event)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PressStripBlock".
 */
export interface PressStripBlock {
  heading?: string | null;
  /**
   * Choose specific quotes, or leave empty to automatically show quotes marked "Feature on homepage / Press page".
   */
  quotes?: (number | PressQuote)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pressStrip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  quote: string;
  /**
   * e.g. "Riverfront Times" or "Julia Gordon-Bramer"
   */
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null)
            | ({
                relationTo: 'books';
                value: number | Book;
              } | null)
            | ({
                relationTo: 'events';
                value: number | Event;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * The words on your Tarot page. Change any text, then press “Publish changes” to put it live. If you empty a box, the original text comes back.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tarotPage".
 */
export interface TarotPage {
  id: number;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  heroText?: string | null;
  /**
   * The button links to your Contact page.
   */
  heroButton?: string | null;
  formatCard?: {
    label?: string | null;
    title?: string | null;
    text?: string | null;
  };
  rateCard?: {
    label?: string | null;
    title?: string | null;
    text?: string | null;
  };
  paymentCard?: {
    label?: string | null;
    title?: string | null;
    text?: string | null;
  };
  bringLabel?: string | null;
  bringStatement?: string | null;
  bringText1?: string | null;
  bringText2?: string | null;
  /**
   * The button links to your Contact page.
   */
  bringButton?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The words on the main Decoding Sylvia Plath page. (The essays themselves are under “Essays”.) Change any text, then press “Publish changes” to put it live. If you empty a box, the original text comes back.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decodingPage".
 */
export interface DecodingPage {
  id: number;
  heroEyebrow?: string | null;
  heroTitle?: string | null;
  /**
   * Press Enter for a new paragraph. Select words and use the buttons above for italic, bold or a link.
   */
  heroIntro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Type just the words — the quotation marks are added for you.
   */
  quote?: string | null;
  quoteSource?: string | null;
  photoCaption?: string | null;
  methodLabel?: string | null;
  methodStatement?: string | null;
  methodText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  credentialsLabel?: string | null;
  /**
   * Add, remove, or reorder as many as you like.
   */
  credentials?:
    | {
        label?: string | null;
        title?: string | null;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  essaysLabel?: string | null;
  /**
   * The number of essays is added automatically in front of this, e.g. “40 essays so far, one per 1956 poem.”
   */
  essaysHeading?: string | null;
  essaysNote?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The heading and introduction at the top of your Books page. (The books themselves are under “Books”.) Press “Publish changes” and it goes live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booksPage".
 */
export interface BooksPage {
  id: number;
  heading?: string | null;
  /**
   * Tip: if you add or remove a book, check this sentence still matches.
   */
  intro?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The heading and introduction at the top of your Events page. (Individual events are under “Upcoming events”.) Press “Publish changes” and it goes live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventsPage".
 */
export interface EventsPage {
  id: number;
  heading?: string | null;
  intro?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The words on your Contact page. Press “Publish changes” and it goes live.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage".
 */
export interface ContactPage {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  intro?: string | null;
  /**
   * Shown to a visitor right after they send you a message.
   */
  successMessage?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site".
 */
export interface Site {
  id: number;
  /**
   * Where "Book a reading" points. Use /contact to route through the form, or paste an external scheduler link.
   */
  bookingUrl?: string | null;
  socials?:
    | {
        platform: 'instagram' | 'x' | 'facebook' | 'youtube' | 'tiktok';
        url: string;
        id?: string | null;
      }[]
    | null;
  announcementEnabled?: boolean | null;
  announcementMessage?: string | null;
  announcementLinkUrl?: string | null;
  announcementLinkLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroHeading?: T;
  heroSubheading?: T;
  heroRichText?: T;
  aboutRichText?: T;
  heroImage?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  modules?:
    | T
    | {
        bioSplit?: T | BioSplitBlockSelect<T>;
        bookShelf?: T | BookShelfBlockSelect<T>;
        eventList?: T | EventListBlockSelect<T>;
        pressStrip?: T | PressStripBlockSelect<T>;
        pullQuote?: T | PullQuoteBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
      };
  aboutImage?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BioSplitBlock_select".
 */
export interface BioSplitBlockSelect<T extends boolean = true> {
  image?: T;
  imagePosition?: T;
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BookShelfBlock_select".
 */
export interface BookShelfBlockSelect<T extends boolean = true> {
  heading?: T;
  books?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventListBlock_select".
 */
export interface EventListBlockSelect<T extends boolean = true> {
  heading?: T;
  mode?: T;
  limit?: T;
  events?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PressStripBlock_select".
 */
export interface PressStripBlockSelect<T extends boolean = true> {
  heading?: T;
  quotes?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock_select".
 */
export interface PullQuoteBlockSelect<T extends boolean = true> {
  quote?: T;
  attribution?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tarotPage_select".
 */
export interface TarotPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroText?: T;
  heroButton?: T;
  formatCard?:
    | T
    | {
        label?: T;
        title?: T;
        text?: T;
      };
  rateCard?:
    | T
    | {
        label?: T;
        title?: T;
        text?: T;
      };
  paymentCard?:
    | T
    | {
        label?: T;
        title?: T;
        text?: T;
      };
  bringLabel?: T;
  bringStatement?: T;
  bringText1?: T;
  bringText2?: T;
  bringButton?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decodingPage_select".
 */
export interface DecodingPageSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroIntro?: T;
  quote?: T;
  quoteSource?: T;
  photoCaption?: T;
  methodLabel?: T;
  methodStatement?: T;
  methodText?: T;
  credentialsLabel?: T;
  credentials?:
    | T
    | {
        label?: T;
        title?: T;
        text?: T;
        id?: T;
      };
  essaysLabel?: T;
  essaysHeading?: T;
  essaysNote?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booksPage_select".
 */
export interface BooksPageSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventsPage_select".
 */
export interface EventsPageSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contactPage_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  intro?: T;
  successMessage?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site_select".
 */
export interface SiteSelect<T extends boolean = true> {
  bookingUrl?: T;
  socials?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  announcementEnabled?: T;
  announcementMessage?: T;
  announcementLinkUrl?: T;
  announcementLinkLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'books';
          value: number | Book;
        } | null)
      | ({
          relationTo: 'events';
          value: number | Event;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}